// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUICockpit
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// AssertMethod1 - Use 'AssertMethod1ExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethod1()
        {
            #region Variable Declarations
            HtmlCustom uIBuscarCustom = this.UIGLOBEPortalInternetEWindow.UIPáginadeinicioDocument.UIBuscarCustom;
            HtmlHyperlink uIItemHyperlink = this.UIGLOBEPortalInternetEWindow.UIPáginadeinicioDocument.UIItemHyperlink;
            #endregion

            // Verify that the 'Id' property of 'Buscar' custom control equals 'sf'
            Assert.AreEqual(this.AssertMethod1ExpectedValues.UIBuscarCustomId, uIBuscarCustom.Id, "Not the equal value");

            // Verify that the 'Id' property of '' link equals 'homeBtn'
            Assert.AreEqual(this.AssertMethod1ExpectedValues.UIItemHyperlinkId, uIItemHyperlink.Id, "Not the same name");
        }
        
        /// <summary>
        /// TestGlobe1 - Use 'TestGlobe1Params' to pass parameters into this method.
        /// </summary>
        public void TestGlobe1()
        {
            #region Variable Declarations
            WinComboBox uIAbrirComboBox = this.UIExecutarWindow.UIItemWindow.UIAbrirComboBox;
            WinEdit uIAbrirEdit = this.UIExecutarWindow.UIItemWindow1.UIAbrirEdit;
            HtmlDiv uISapUshellLoadingOverPane = this.UIGLOBEPortalInternetEWindow.UIGLOBEPortalDocument.UISapUshellLoadingOverPane;
            HtmlDiv uIApplicationResolutioPane = this.UIGLOBEPortalInternetEWindow.UIGLOBEPortalDocument.UIApplicationResolutioPane;
            HtmlCustom uIItemCustom = this.UIGLOBEPortalInternetEWindow.UIGLOBEPortalDocument.UIUIComp_2Pane.UIItemCustom;
            HtmlCustom uIOpcionesCustom = this.UIGLOBEPortalInternetEWindow.UIGLOBEPortalDocument.UIOpcionesCustom;
            HtmlDiv uIItemPane = this.UIGLOBEPortalInternetEWindow.UIGLOBEPortalDocument.UIOpcionesdeusuarioPane.UIItemPane;
            HtmlDiv uIItemPane1 = this.UIGLOBEPortalInternetEWindow.UIGLOBEPortalDocument.UICancelarPane.UIItemPane;
            HtmlDiv uISapuiblocklayerpopupPane = this.UIGLOBEPortalInternetEWindow.UIGLOBEPortalDocument.UISapuiblocklayerpopupPane;
            HtmlCustom uIItemCustom1 = this.UIGLOBEPortalInternetEWindow.UIGLOBEPortalDocument.UIUIComp_0Pane.UIItemCustom;
            HtmlHyperlink uIItemHyperlink = this.UIGLOBEPortalInternetEWindow.UIGLOBEPortalDocument.UIItemHyperlink;
            HtmlDiv uIMyNestléPane = this.UIGLOBEPortalInternetEWindow.UIGLOBEPortalDocument.UIMyNestléPane;
            HtmlCustom uIItemCustom2 = this.UIGLOBEPortalInternetEWindow.UIGLOBEPortalDocument.UIMyNestléMipáginadeinPane.UIItemCustom;
            HtmlDiv uI__epcontent3Pane = this.UIGLOBEPortalInternetEWindow.UIGLOBEPortalDocument.UI__epcontent3Pane;
            HtmlDiv uI__epcontent40Pane = this.UIGLOBEPortalInternetEWindow.UIGLOBEPortalDocument.UI__epcontent40Pane;
            HtmlEdit uICatalogSearchIEdit = this.UIGLOBEPortalInternetEWindow.UIGLOBEPortalDocument.UICatalogSearchIEdit;
            HtmlDiv uICatalogSearchresetPane = this.UIGLOBEPortalInternetEWindow.UIGLOBEPortalDocument.UICatalogSearchresetPane;
            #endregion

            // Press keyboard shortcut keys 'Windows + r'
            Keyboard.SendKeys(this.TestGlobe1Params.SendKeys, ModifierKeys.Windows);

            // Select 'https://globe7ams.nestle.com:26001/irj/portal#ResolutionCockpit-manage?sap-system=R3AA1' in 'Abrir:' combo box
            uIAbrirComboBox.EditableItem = this.TestGlobe1Params.UIAbrirComboBoxEditableItem;

            // Type '{Enter}' in 'Abrir:' text box
            Keyboard.SendKeys(uIAbrirEdit, this.TestGlobe1Params.UIAbrirEditSendKeys, ModifierKeys.None);

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'sapUshellLoadingOverlay' pane at (1, 1)
            Mouse.Hover(uISapUshellLoadingOverPane, new Point(1, 1));

            // Mouse hover 'application-ResolutionCockpit-manage-component---m...' pane at (1, 1)
            Mouse.Hover(uIApplicationResolutioPane, new Point(1, 1));

            // Mouse hover  custom control at (1, 1)
            Mouse.Hover(uIItemCustom, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Opciones' custom control
            Mouse.Click(uIOpcionesCustom, new Point(66, 28));

            // Click pane
            Mouse.Click(uIItemPane, new Point(69, 11));

            // Click pane
            Mouse.Click(uIItemPane1, new Point(51, 15));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'sap-ui-blocklayer-popup' pane at (1, 1)
            Mouse.Hover(uISapuiblocklayerpopupPane, new Point(1, 1));

            // Mouse hover  custom control at (1, 1)
            Mouse.Hover(uIItemCustom1, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click '' link
            Mouse.Click(uIItemHyperlink, new Point(23, 46));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'My Nestlé' pane at (1, 1)
            Mouse.Hover(uIMyNestléPane, new Point(1, 1));

            // Mouse hover  custom control at (1, 1)
            Mouse.Hover(uIItemCustom2, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click '__epcontent3' pane
            Mouse.Click(uI__epcontent3Pane, new Point(137, 50));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover '__epcontent40' pane at (1, 1)
            Mouse.Hover(uI__epcontent40Pane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'catalogSearch-I' text box
            Mouse.Click(uICatalogSearchIEdit, new Point(128, 20));

            // Click 'catalogSearch-reset' pane
            Mouse.Click(uICatalogSearchresetPane, new Point(11, 18));

            // Type 'Paylisp' in 'catalogSearch-I' text box
            uICatalogSearchIEdit.Text = this.TestGlobe1Params.UICatalogSearchIEditText;

            // Type '{Enter}' in 'catalogSearch-I' text box
            Keyboard.SendKeys(uICatalogSearchIEdit, this.TestGlobe1Params.UICatalogSearchIEditSendKeys, ModifierKeys.None);
        }
        
        #region Properties
        public virtual AssertMethod1ExpectedValues AssertMethod1ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod1ExpectedValues == null))
                {
                    this.mAssertMethod1ExpectedValues = new AssertMethod1ExpectedValues();
                }
                return this.mAssertMethod1ExpectedValues;
            }
        }
        
        public virtual TestGlobe1Params TestGlobe1Params
        {
            get
            {
                if ((this.mTestGlobe1Params == null))
                {
                    this.mTestGlobe1Params = new TestGlobe1Params();
                }
                return this.mTestGlobe1Params;
            }
        }
        
        public UIExecutarWindow UIExecutarWindow
        {
            get
            {
                if ((this.mUIExecutarWindow == null))
                {
                    this.mUIExecutarWindow = new UIExecutarWindow();
                }
                return this.mUIExecutarWindow;
            }
        }
        
        public UIGLOBEPortalInternetEWindow UIGLOBEPortalInternetEWindow
        {
            get
            {
                if ((this.mUIGLOBEPortalInternetEWindow == null))
                {
                    this.mUIGLOBEPortalInternetEWindow = new UIGLOBEPortalInternetEWindow();
                }
                return this.mUIGLOBEPortalInternetEWindow;
            }
        }
        #endregion
        
        #region Fields
        private AssertMethod1ExpectedValues mAssertMethod1ExpectedValues;
        
        private TestGlobe1Params mTestGlobe1Params;
        
        private UIExecutarWindow mUIExecutarWindow;
        
        private UIGLOBEPortalInternetEWindow mUIGLOBEPortalInternetEWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class AssertMethod1ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Id' property of 'Buscar' custom control equals 'sf'
        /// </summary>
        public string UIBuscarCustomId = "sf";
        
        /// <summary>
        /// Verify that the 'Id' property of '' link equals 'homeBtn'
        /// </summary>
        public string UIItemHyperlinkId = "homeBtn";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestGlobe1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class TestGlobe1Params
    {
        
        #region Fields
        /// <summary>
        /// Press keyboard shortcut keys 'Windows + r'
        /// </summary>
        public string SendKeys = "r";
        
        /// <summary>
        /// Select 'https://globe7ams.nestle.com:26001/irj/portal#ResolutionCockpit-manage?sap-system=R3AA1' in 'Abrir:' combo box
        /// </summary>
        public string UIAbrirComboBoxEditableItem = "https://globe7ams.nestle.com:26001/irj/portal#ResolutionCockpit-manage?sap-system" +
            "=R3AA1";
        
        /// <summary>
        /// Type '{Enter}' in 'Abrir:' text box
        /// </summary>
        public string UIAbrirEditSendKeys = "{Enter}";
        
        /// <summary>
        /// Type 'Paylisp' in 'catalogSearch-I' text box
        /// </summary>
        public string UICatalogSearchIEditText = "Paylisp";
        
        /// <summary>
        /// Type '{Enter}' in 'catalogSearch-I' text box
        /// </summary>
        public string UICatalogSearchIEditSendKeys = "{Enter}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIExecutarWindow : WinWindow
    {
        
        public UIExecutarWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Executar";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Executar");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        
        private UIItemWindow1 mUIItemWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "12298";
            this.WindowTitles.Add("Executar");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIAbrirComboBox
        {
            get
            {
                if ((this.mUIAbrirComboBox == null))
                {
                    this.mUIAbrirComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIAbrirComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "Abrir:";
                    this.mUIAbrirComboBox.WindowTitles.Add("Executar");
                    #endregion
                }
                return this.mUIAbrirComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIAbrirComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1001";
            this.WindowTitles.Add("Executar");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAbrirEdit
        {
            get
            {
                if ((this.mUIAbrirEdit == null))
                {
                    this.mUIAbrirEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAbrirEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Abrir:";
                    this.mUIAbrirEdit.WindowTitles.Add("Executar");
                    #endregion
                }
                return this.mUIAbrirEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAbrirEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIGLOBEPortalInternetEWindow : BrowserWindow
    {
        
        public UIGLOBEPortalInternetEWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "GLOBE Portal";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("GLOBE Portal");
            this.WindowTitles.Add("Cockpit de resolución");
            this.WindowTitles.Add("Página de inicio");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIGLOBEPortalDocument UIGLOBEPortalDocument
        {
            get
            {
                if ((this.mUIGLOBEPortalDocument == null))
                {
                    this.mUIGLOBEPortalDocument = new UIGLOBEPortalDocument(this);
                }
                return this.mUIGLOBEPortalDocument;
            }
        }
        
        public UIPáginadeinicioDocument UIPáginadeinicioDocument
        {
            get
            {
                if ((this.mUIPáginadeinicioDocument == null))
                {
                    this.mUIPáginadeinicioDocument = new UIPáginadeinicioDocument(this);
                }
                return this.mUIPáginadeinicioDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIGLOBEPortalDocument mUIGLOBEPortalDocument;
        
        private UIPáginadeinicioDocument mUIPáginadeinicioDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIGLOBEPortalDocument : HtmlDocument
    {
        
        public UIGLOBEPortalDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "GLOBE Portal";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/irj/portal";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://globe7ams.nestle.com:26001/irj/portal#ResolutionCockpit-manage?sap-system" +
                "=R3AA1";
            this.WindowTitles.Add("GLOBE Portal");
            this.WindowTitles.Add("Cockpit de resolución");
            this.WindowTitles.Add("Página de inicio");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UISapUshellLoadingOverPane
        {
            get
            {
                if ((this.mUISapUshellLoadingOverPane == null))
                {
                    this.mUISapUshellLoadingOverPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUISapUshellLoadingOverPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "sapUshellLoadingOverlay";
                    this.mUISapUshellLoadingOverPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUISapUshellLoadingOverPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUISapUshellLoadingOverPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUISapUshellLoadingOverPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "sapUshellLoadingOverlayStyle";
                    this.mUISapUshellLoadingOverPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"sapUshellLoadingOverlayStyle\" id=\"sapUshellLoadingOverlay\" style=\"visibili" +
                        "ty: visible; z-index: 8;\"";
                    this.mUISapUshellLoadingOverPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "1";
                    this.mUISapUshellLoadingOverPane.WindowTitles.Add("GLOBE Portal");
                    #endregion
                }
                return this.mUISapUshellLoadingOverPane;
            }
        }
        
        public HtmlDiv UIApplicationResolutioPane
        {
            get
            {
                if ((this.mUIApplicationResolutioPane == null))
                {
                    this.mUIApplicationResolutioPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIApplicationResolutioPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "application-ResolutionCockpit-manage-component---main--idSfbOrderFilter-toolbar";
                    this.mUIApplicationResolutioPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIApplicationResolutioPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Estándar\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nSuprimir barra";
                    this.mUIApplicationResolutioPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIApplicationResolutioPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "sapMIBar sapMTB sapMTB-Auto-CTX sapMTBInactive sapMTBNewFlex sapUiCompFilterBarTo" +
                        "olbar sapUiCompFilterBarToolbarMarker";
                    this.mUIApplicationResolutioPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = @"class=""sapMIBar sapMTB sapMTB-Auto-CTX sapMTBInactive sapMTBNewFlex sapUiCompFilterBarToolbar sapUiCompFilterBarToolbarMarker"" id=""application-ResolutionCockpit-manage-component---main--idSfbOrderFilter-toolbar"" role=""toolbar"" data-sap-ui=""application-ResolutionCockpit-manage-component---main--idSfbOrderFilter-toolbar"" data-sap-ui-fastnavgroup=""true""";
                    this.mUIApplicationResolutioPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "133";
                    this.mUIApplicationResolutioPane.WindowTitles.Add("GLOBE Portal");
                    #endregion
                }
                return this.mUIApplicationResolutioPane;
            }
        }
        
        public UIUIComp_2Pane UIUIComp_2Pane
        {
            get
            {
                if ((this.mUIUIComp_2Pane == null))
                {
                    this.mUIUIComp_2Pane = new UIUIComp_2Pane(this);
                }
                return this.mUIUIComp_2Pane;
            }
        }
        
        public HtmlCustom UIOpcionesCustom
        {
            get
            {
                if ((this.mUIOpcionesCustom == null))
                {
                    this.mUIOpcionesCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIOpcionesCustom.SearchProperties["TagName"] = "A";
                    this.mUIOpcionesCustom.SearchProperties["Id"] = "actionsBtn";
                    this.mUIOpcionesCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIOpcionesCustom.FilterProperties["Class"] = "sapUshellShellHeadAction sapUshellShellHeadSeparator";
                    this.mUIOpcionesCustom.FilterProperties["ControlDefinition"] = "tabindex=\"0\" title=\"Opciones\" class=\"sap";
                    this.mUIOpcionesCustom.FilterProperties["TagInstance"] = "3";
                    this.mUIOpcionesCustom.WindowTitles.Add("Cockpit de resolución");
                    #endregion
                }
                return this.mUIOpcionesCustom;
            }
        }
        
        public UIOpcionesdeusuarioPane UIOpcionesdeusuarioPane
        {
            get
            {
                if ((this.mUIOpcionesdeusuarioPane == null))
                {
                    this.mUIOpcionesdeusuarioPane = new UIOpcionesdeusuarioPane(this);
                }
                return this.mUIOpcionesdeusuarioPane;
            }
        }
        
        public UICancelarPane UICancelarPane
        {
            get
            {
                if ((this.mUICancelarPane == null))
                {
                    this.mUICancelarPane = new UICancelarPane(this);
                }
                return this.mUICancelarPane;
            }
        }
        
        public HtmlDiv UISapuiblocklayerpopupPane
        {
            get
            {
                if ((this.mUISapuiblocklayerpopupPane == null))
                {
                    this.mUISapuiblocklayerpopupPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUISapuiblocklayerpopupPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "sap-ui-blocklayer-popup";
                    this.mUISapuiblocklayerpopupPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUISapuiblocklayerpopupPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUISapuiblocklayerpopupPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUISapuiblocklayerpopupPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "sapUiBLy sapMDialogBlockLayerInit";
                    this.mUISapuiblocklayerpopupPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "tabindex=\"0\" class=\"sapUiBLy sapMDialogBlockLayerInit\" id=\"sap-ui-blocklayer-popu" +
                        "p\" style=\"visibility: visible; z-index: 18;\"";
                    this.mUISapuiblocklayerpopupPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "46";
                    this.mUISapuiblocklayerpopupPane.WindowTitles.Add("Cockpit de resolución");
                    #endregion
                }
                return this.mUISapuiblocklayerpopupPane;
            }
        }
        
        public UIUIComp_0Pane UIUIComp_0Pane
        {
            get
            {
                if ((this.mUIUIComp_0Pane == null))
                {
                    this.mUIUIComp_0Pane = new UIUIComp_0Pane(this);
                }
                return this.mUIUIComp_0Pane;
            }
        }
        
        public HtmlHyperlink UIItemHyperlink
        {
            get
            {
                if ((this.mUIItemHyperlink == null))
                {
                    this.mUIItemHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIItemHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "homeBtn";
                    this.mUIItemHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIItemHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIItemHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/irj/portal";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Página de inicio";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://globe7ams.nestle.com:26001/irj/portal#Shell-home";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "sapUshellShellHeadItm sapUshellShellHeadItmSep";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "tabindex=\"0\" title=\"Página de inicio\" cl";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIItemHyperlink.WindowTitles.Add("Cockpit de resolución");
                    #endregion
                }
                return this.mUIItemHyperlink;
            }
        }
        
        public HtmlDiv UIMyNestléPane
        {
            get
            {
                if ((this.mUIMyNestléPane == null))
                {
                    this.mUIMyNestléPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIMyNestléPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "__container4-dashboardGroups-id-1542225852609-385-title";
                    this.mUIMyNestléPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIMyNestléPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "My Nestlé";
                    this.mUIMyNestléPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIMyNestléPane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIMyNestléPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"__container4-dashboardGroups-id-1542225852609-385-title\"";
                    this.mUIMyNestléPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "82";
                    this.mUIMyNestléPane.WindowTitles.Add("Página de inicio");
                    #endregion
                }
                return this.mUIMyNestléPane;
            }
        }
        
        public UIMyNestléMipáginadeinPane UIMyNestléMipáginadeinPane
        {
            get
            {
                if ((this.mUIMyNestléMipáginadeinPane == null))
                {
                    this.mUIMyNestléMipáginadeinPane = new UIMyNestléMipáginadeinPane(this);
                }
                return this.mUIMyNestléMipáginadeinPane;
            }
        }
        
        public HtmlDiv UI__epcontent3Pane
        {
            get
            {
                if ((this.mUI__epcontent3Pane == null))
                {
                    this.mUI__epcontent3Pane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUI__epcontent3Pane.SearchProperties[HtmlDiv.PropertyNames.Id] = "__epcontent3";
                    this.mUI__epcontent3Pane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUI__epcontent3Pane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUI__epcontent3Pane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUI__epcontent3Pane.FilterProperties[HtmlDiv.PropertyNames.Class] = "sapEPTileImage";
                    this.mUI__epcontent3Pane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"sapEPTileImage\" id=\"__epcontent3\" style=\'background: url(\"/com.sap.portal." +
                        "resourcerepository/repo/nestle_mobile/flpicons/appfinder_es.png\") no-repeat righ" +
                        "t bottom / 100% 100%; height: 100% !important;\' data-sap-ui=\"__epcontent3\"";
                    this.mUI__epcontent3Pane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "334";
                    this.mUI__epcontent3Pane.WindowTitles.Add("Página de inicio");
                    #endregion
                }
                return this.mUI__epcontent3Pane;
            }
        }
        
        public HtmlDiv UI__epcontent40Pane
        {
            get
            {
                if ((this.mUI__epcontent40Pane == null))
                {
                    this.mUI__epcontent40Pane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUI__epcontent40Pane.SearchProperties[HtmlDiv.PropertyNames.Id] = "__epcontent40";
                    this.mUI__epcontent40Pane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUI__epcontent40Pane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUI__epcontent40Pane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUI__epcontent40Pane.FilterProperties[HtmlDiv.PropertyNames.Class] = "sapMFrameTypeOneByOne sapMTileCnt";
                    this.mUI__epcontent40Pane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"sapMFrameTypeOneByOne sapMTileCnt\" id=\"__epcontent40\" data-sap-ui=\"__epcon" +
                        "tent40\"";
                    this.mUI__epcontent40Pane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "715";
                    this.mUI__epcontent40Pane.WindowTitles.Add("Página de inicio");
                    #endregion
                }
                return this.mUI__epcontent40Pane;
            }
        }
        
        public HtmlEdit UICatalogSearchIEdit
        {
            get
            {
                if ((this.mUICatalogSearchIEdit == null))
                {
                    this.mUICatalogSearchIEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICatalogSearchIEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "catalogSearch-I";
                    this.mUICatalogSearchIEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUICatalogSearchIEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUICatalogSearchIEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICatalogSearchIEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUICatalogSearchIEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "sapMSFI";
                    this.mUICatalogSearchIEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "tabindex=\"0\" class=\"sapMSFI\" id=\"catalog";
                    this.mUICatalogSearchIEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "10";
                    this.mUICatalogSearchIEdit.WindowTitles.Add("Página de inicio");
                    #endregion
                }
                return this.mUICatalogSearchIEdit;
            }
        }
        
        public HtmlDiv UICatalogSearchresetPane
        {
            get
            {
                if ((this.mUICatalogSearchresetPane == null))
                {
                    this.mUICatalogSearchresetPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUICatalogSearchresetPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "catalogSearch-reset";
                    this.mUICatalogSearchresetPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUICatalogSearchresetPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUICatalogSearchresetPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUICatalogSearchresetPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "sapMSFB sapMSFR";
                    this.mUICatalogSearchresetPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"sapMSFB sapMSFR\" id=\"catalogSearch-reset\"";
                    this.mUICatalogSearchresetPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "699";
                    this.mUICatalogSearchresetPane.WindowTitles.Add("Página de inicio");
                    #endregion
                }
                return this.mUICatalogSearchresetPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUISapUshellLoadingOverPane;
        
        private HtmlDiv mUIApplicationResolutioPane;
        
        private UIUIComp_2Pane mUIUIComp_2Pane;
        
        private HtmlCustom mUIOpcionesCustom;
        
        private UIOpcionesdeusuarioPane mUIOpcionesdeusuarioPane;
        
        private UICancelarPane mUICancelarPane;
        
        private HtmlDiv mUISapuiblocklayerpopupPane;
        
        private UIUIComp_0Pane mUIUIComp_0Pane;
        
        private HtmlHyperlink mUIItemHyperlink;
        
        private HtmlDiv mUIMyNestléPane;
        
        private UIMyNestléMipáginadeinPane mUIMyNestléMipáginadeinPane;
        
        private HtmlDiv mUI__epcontent3Pane;
        
        private HtmlDiv mUI__epcontent40Pane;
        
        private HtmlEdit mUICatalogSearchIEdit;
        
        private HtmlDiv mUICatalogSearchresetPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIUIComp_2Pane : HtmlDiv
    {
        
        public UIUIComp_2Pane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "UIComp_2";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Excepciones no tomadasÓrdenesEntregaFact";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "v-info";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "tabindex=\"0\" class=\"v-info\" id=\"UIComp_2\" style=\"width: 100%; height: 100%; font-" +
                "size: 10px; position: relative; box-sizing: border-box;\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "124";
            this.WindowTitles.Add("Cockpit de resolución");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["TagName"] = "rect";
                    this.mUIItemCustom.SearchProperties["Id"] = null;
                    this.mUIItemCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIItemCustom.FilterProperties["Class"] = "v-bound";
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = "xmlns=\"http://www.w3.org/2000/svg\" class";
                    this.mUIItemCustom.FilterProperties["TagInstance"] = "2";
                    this.mUIItemCustom.WindowTitles.Add("Cockpit de resolución");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIOpcionesdeusuarioPane : HtmlDiv
    {
        
        public UIOpcionesdeusuarioPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "userPreferencesButton-inner";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Opciones de usuario";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "sapMBtnHoverable sapMBtnIconFirst sapMBtnInner sapMBtnText sapMBtnTransparent sap" +
                "MFocusable sapMIE";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"sapMBtnHoverable sapMBtnIconFirst sapMBtnInner sapMBtnText sapMBtnTranspar" +
                "ent sapMFocusable sapMIE\" id=\"userPreferencesButton-inner\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "8";
            this.WindowTitles.Add("Cockpit de resolución");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "sapMBtnFocusDiv";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"sapMBtnFocusDiv\"";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "9";
                    this.mUIItemPane.WindowTitles.Add("Cockpit de resolución");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIItemPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICancelarPane : HtmlDiv
    {
        
        public UICancelarPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "cancelButton-inner";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Cancelar";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "sapMBtnDefault sapMBtnHoverable sapMBtnInner sapMBtnText sapMFocusable sapMIE";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"sapMBtnDefault sapMBtnHoverable sapMBtnInner sapMBtnText sapMFocusable sap" +
                "MIE\" id=\"cancelButton-inner\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "43";
            this.WindowTitles.Add("Cockpit de resolución");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "sapMBtnFocusDiv";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"sapMBtnFocusDiv\"";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "44";
                    this.mUIItemPane.WindowTitles.Add("Cockpit de resolución");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIItemPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIUIComp_0Pane : HtmlDiv
    {
        
        public UIUIComp_0Pane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "UIComp_0";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Excepciones abiertasÓrdenesEntregaFactur";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "v-info";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "tabindex=\"0\" class=\"v-info\" id=\"UIComp_0\" style=\"width: 100%; height: 100%; font-" +
                "size: 10px; position: relative; box-sizing: border-box;\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "95";
            this.WindowTitles.Add("Cockpit de resolución");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["TagName"] = "rect";
                    this.mUIItemCustom.SearchProperties["Id"] = null;
                    this.mUIItemCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIItemCustom.FilterProperties["Class"] = "v-plot-bound v-bound v-zoom-plot";
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = "xmlns=\"http://www.w3.org/2000/svg\" class";
                    this.mUIItemCustom.FilterProperties["TagInstance"] = "16";
                    this.mUIItemCustom.WindowTitles.Add("Cockpit de resolución");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMyNestléMipáginadeinPane : HtmlDiv
    {
        
        public UIMyNestléMipáginadeinPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "anchorNavigationBar";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "My Nestlé\r\n\r\n\r\nMi página de inicio";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "sapContrastPlus sapMHeader-CTX sapMIBar-CTX sapMPageHeader sapUshellAnchorNavigat" +
                "ionBar";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"sapContrastPlus sapMHeader-CTX sapMIBar-CTX sapMPageHeader sapUshellAnchor" +
                "NavigationBar\" id=\"anchorNavigationBar\" data-sap-ui=\"anchorNavigationBar\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "63";
            this.WindowTitles.Add("Página de inicio");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["TagName"] = "UL";
                    this.mUIItemCustom.SearchProperties["Id"] = null;
                    this.mUIItemCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIItemCustom.FilterProperties["Class"] = "sapUshellAnchorNavigationBarItemsScroll";
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = "tabindex=\"0\" class=\"sapUshellAnchorNavig";
                    this.mUIItemCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIItemCustom.WindowTitles.Add("Página de inicio");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPáginadeinicioDocument : HtmlDocument
    {
        
        public UIPáginadeinicioDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Página de inicio";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/irj/portal";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://globe7ams.nestle.com:26001/irj/portal#Shell-home&/appFinder/catalog/%7B%2" +
                "2catalogSelector%22:null,%22tileFilter%22:%22%22,%22tagFilter%22:%22%5B%5D%22,%2" +
                "2targetGroup%22:%22%22%7D";
            this.WindowTitles.Add("Página de inicio");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIOpcionesCustom
        {
            get
            {
                if ((this.mUIOpcionesCustom == null))
                {
                    this.mUIOpcionesCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIOpcionesCustom.SearchProperties["TagName"] = "A";
                    this.mUIOpcionesCustom.SearchProperties["Id"] = "actionsBtn";
                    this.mUIOpcionesCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIOpcionesCustom.FilterProperties["Class"] = "sapUshellShellHeadAction sapUshellShellHeadSeparator";
                    this.mUIOpcionesCustom.FilterProperties["ControlDefinition"] = "tabindex=\"0\" title=\"Opciones\" class=\"sap";
                    this.mUIOpcionesCustom.FilterProperties["TagInstance"] = "3";
                    this.mUIOpcionesCustom.WindowTitles.Add("Página de inicio");
                    #endregion
                }
                return this.mUIOpcionesCustom;
            }
        }
        
        public HtmlCustom UIBuscarCustom
        {
            get
            {
                if ((this.mUIBuscarCustom == null))
                {
                    this.mUIBuscarCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIBuscarCustom.SearchProperties["TagName"] = "A";
                    this.mUIBuscarCustom.SearchProperties["Id"] = "sf";
                    this.mUIBuscarCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIBuscarCustom.FilterProperties["Class"] = "sapUshellShellHeadItm";
                    this.mUIBuscarCustom.FilterProperties["ControlDefinition"] = "tabindex=\"0\" title=\"Buscar\" class=\"sapUs";
                    this.mUIBuscarCustom.FilterProperties["TagInstance"] = "2";
                    this.mUIBuscarCustom.WindowTitles.Add("Página de inicio");
                    #endregion
                }
                return this.mUIBuscarCustom;
            }
        }
        
        public HtmlHyperlink UIItemHyperlink
        {
            get
            {
                if ((this.mUIItemHyperlink == null))
                {
                    this.mUIItemHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIItemHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "homeBtn";
                    this.mUIItemHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIItemHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIItemHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/irj/portal";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Página de inicio";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://globe7ams.nestle.com:26001/irj/portal#Shell-home";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "sapUshellShellHeadItm sapUshellShellHeadItmSep";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "tabindex=\"0\" title=\"Página de inicio\" cl";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIItemHyperlink.WindowTitles.Add("Página de inicio");
                    #endregion
                }
                return this.mUIItemHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIOpcionesCustom;
        
        private HtmlCustom mUIBuscarCustom;
        
        private HtmlHyperlink mUIItemHyperlink;
        #endregion
    }
}
